export const bgImages: { [key: string]: string } = {
	'Web Development': "lg:bg-[url('/images/aboutServices/bg-web.webp')]",
	'Mobile App Development': "-left-24 lg:bg-[url('/images/aboutServices/bg-mobile.webp')]",
	'TV & Roku Development': "lg:bg-[url('/images/aboutServices/bg-tv.webp')]",
	'UI/UX Design': "lg:bg-[url('/images/aboutServices/bg-ux.webp')]",
	'Software Testing': "-left-8 lg:bg-[url('/images/aboutServices/bg-qa.webp')]",
	Unity: "lg:bg-[url('/images/aboutServices/bg-ai.webp')]",
	'AR/VR': "lg:bg-[url('/images/aboutServices/bg-ar.webp')]",
	DevOps: "lg:bg-[url('/images/aboutServices/bg-devops.webp')]",
	IoT: "lg:bg-[url('/images/aboutServices/bg-internet.webp')]",
	'AI/ML': "lg:bg-[url('/images/aboutServices/bg-proccessor.webp')]",
	'Project Management': "lg:bg-[url('/images/aboutServices/bg-project.webp')]",
	'Dedicated Team': "lg:bg-[url('/images/aboutServices/bg-dedicated.webp')]",
	'Веб розробка': "lg:bg-[url('/images/aboutServices/bg-web.webp')]",
	'Мобільна розробка': "-left-24 lg:bg-[url('/images/aboutServices/bg-mobile.webp')]",
	'Розробка для TV & Roku': "lg:bg-[url('/images/aboutServices/bg-tv.webp')]",
	'Тестування програмного забезпечення': "-left-8 lg:bg-[url('/images/aboutServices/bg-qa.webp')]",
	'Інтернет речей': "lg:bg-[url('/images/aboutServices/bg-internet.webp')]",
	'Проєктний менеджмент': "lg:bg-[url('/images/aboutServices/bg-project.webp')]",
}
